name: Create and deploy a @lipwig prerelease
run-name: ${{ gitea.actor }} is creating a @lipwig prerelease
on:
    push:
        branches:
            - develop
            - feature/reconnection
        tags-ignore:
            - v[0-9]+.[0-9]+.[0-9]+
            - v[0-9]+.[0-9]+.[0-9]+-next.[0-9]+
jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Setup NPM
        run: |
            echo user=willowhayward >> .npmrc
            echo //registry.yarnpkg.com/:_authToken=${{ secrets.CI_NPM_TOKEN }} >> .npmrc
      - name: Setup Git
        run: |
            git config user.email "willow@whc.fyi"
            git config user.name "Willow Hayward"
            git remote add gitea https://willowhayward:${{ secrets.CI_GIT_TOKEN }}@git.whc.fyi/WillowHayward/lipwig.git
      - name: Install dependencies
        run: |
            corepack enable
            yarn install
      - name: Build and deploy prerelease
        run: yarn nx run workspace:prerelease
      - name: Push changes to repo
        run: |
            git push gitea --tags
            git push gitea
