on:
  issues:
    types: 
      - labeled
      - assigned

jobs:
  ticket-management:
    runs-on: ubuntu-latest
    steps:
      - name: Echo event payload
        run: cat ${GITHUB_EVENT_PATH} | ./scripts/ticket-management.sh
